### ISSUE TITLE
CSS三栏布局

### ISSUE THREAD

**Issue by hcnicepink** [hcnicepink/hcnicepink.github.io#2]
# 圣杯布局

## 1.首先给出基本的html结构和css样式
```html
<div id="container">
  <div id="main">main</div>
  <div id="left">left</div>
  <div id="right">right</div>
</div>
```

```css
* { box-sizing: border-box; }

#container {
  width: 100%;
  height: 200px;
  background-color: teal;
  overflow: hidden;
}

#main {
  float: left;
  min-width: 400px;
  width: 100%;
  height: 200px;
  background-color: olive;
}

#left {
  float: left;
  width: 100px;
  height: 200px;
  background-color: orange;
}

#right {
  float: left;
  width: 150px;
  height: 200px;
  background-color: green;
}
```
![三栏没有在一行显示](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/1.png?raw=true)

## 2.为左右两栏添加负边距拉回第一行

```css
#left {
  margin-left: -100%;
}
#right {
  margin-left: -150px;
}
```

![此时已经显示为一行(但是main被遮住了)](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/2.png?raw=true)

## 3.为container添加padding空出左右块的位置

```css
#container {
  padding: 0 150px 0 100px;
}
```
![此时左右空出宽度但是中间被挤进去了(main还是遮住的状态)](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/3.png?raw=true)

## 4.为左右块添加相对位移

```css
#left {
    position: relative;
    left: -100px;
}
#right {
    position: relative;
    right: 150px;
}
```

![此时圣杯布局就完成了](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/4.png?raw=true)

[请查看示例](https://codepen.io/nicepink/pen/wmBybQ)
还有一种方法就是将**right盒子**的样式改为 `{ margin-right: -150px; }` 这样就无需使用相对定位了

# 双飞翼布局

## 1.首先给出基本的html结构和css样式

```html
<div id="main">
  <div id="main-inner">main-inner</div>
</div>
<div id="left">left</div>
<div id="right">right</div>
```

```css
* { box-sizing: border-box; }

body {
  main-width: 400px;
}

#main {
  float: left;
  min-width: 400px;
  width: 100%;
  height: 200px;
  background-color: teal;
}

#main-inner {
  margin: 0 150px 0 100px;
  height: 200px;
  background-color: olive;
}

#left {
  float: left;
  width: 100px;
  height: 200px;
  background-color: orange;
}

#right {
  float: left;
  width: 150px;
  height: 200px;
  background-color: green;
}
```

![三栏没有在一行显示](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/5.png?raw=true)

## 2.为左右两栏添加负边距拉回第一行

```css
#left {
  margin-left: -100%;
}
#right {
  margin-left: -150px;
}
```

![此时已经显示为一行](https://github.com/hcnicepink/hcnicepink.github.io/blob/master/images/2/6.png?raw=true)

[这里是示例](https://codepen.io/nicepink/pen/GxJKvE)
